ALTER TABLE "users" ADD COLUMN "watchedPrivacy" TEXT NOT NULL DEFAULT 'FRIENDS';
ALTER TABLE "users" ADD COLUMN "likedPrivacy" TEXT NOT NULL DEFAULT 'FRIENDS';
ALTER TABLE "users" ADD COLUMN "watchlistPrivacy" TEXT NOT NULL DEFAULT 'ONLY_ME';
